### ISSUE TITLE
同学,你的Party-Lecture-Cracker项目文件还有吗

### ISSUE THREAD

**Issue by Crystalxmz** [herobrine1010/tongxinyun_spiders#2]

**Comment by herobrine1010** [comment]
Hi there!
&nbsp; &nbsp; Glad to receive your issue. To play it safe, would you please send me a snapshot of your site where you may apply my project? I would like to share the code only if you accept not to abuse it.
Best Regards
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Crystalxmz"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月17日(星期三) 晚上9:04
收件人:&nbsp;"herobrine1010/tongxinyun_spiders"<tongxinyun_spiders@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[herobrine1010/tongxinyun_spiders] 同学,你的Party-Lecture-Cracker项目文件还有吗 (#2)

**Comment by herobrine1010** [comment]
Hi there!
    Glad to receive your issue. To play it safe, would you please send me a snapshot of your site where you may apply my project? I would like to share the code only if you accept not to abuse it.
                                                                                                                                         Best Regards

**Comment by Crystalxmz** [comment]
![Snipaste](https://user-images.githubusercontent.com/50786945/84977724-a7973180-b15d-11ea-96c2-7da08aa5b086.png)
可以用在这吗?

**Comment by herobrine1010** [comment]
Got it ! I've sent an invitation to you to access the repository. Hope that might help you.
Or <a href="https://github.com/herobrine1010/Party-Lecture-Cracker-DEPRECATED">click here </a>

**Comment by Crystalxmz** [comment]
十分感谢!

**Comment by herobrine1010** [comment]
Glad you appreciate it. You are recommended to fork this project to your own repository for further usage. as I might later close this issue and remove you from the collaborators sometime. Anyway It's all about safety and PLEASE DON NOT share it to anyone else.

**Comment by Crystalxmz** [comment]
好的,使用效果一流,再次表达一下感谢!
